version: '2'
services:
  spark:
    build: .
    ports:
      - "8081:8081"
      - "8080:8080"
      - "4040:4040"
    volumes:
      - .:/app
  es:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      HOSTNAME: development
    command: ["elasticsearch"]